# Generated by Django 3.1.5 on 2021-03-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kleague1_2021_1r',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('matches', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('wons', models.IntegerField(blank=True, null=True)),
                ('draws', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('getgoals', models.IntegerField(blank=True, null=True)),
                ('lostgoals', models.IntegerField(blank=True, null=True)),
                ('get_losts', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('fouls', models.IntegerField(blank=True, null=True)),
                ('logos', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'k1_1라운드',
                'ordering': ('-points', '-getgoals'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kleague1_2021_2r',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('matches', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('wons', models.IntegerField(blank=True, null=True)),
                ('draws', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('getgoals', models.IntegerField(blank=True, null=True)),
                ('lostgoals', models.IntegerField(blank=True, null=True)),
                ('get_losts', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('fouls', models.IntegerField(blank=True, null=True)),
                ('logos', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'k1_2라운드',
                'ordering': ('-points', '-getgoals'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kleague1_2021_3r',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('matches', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('wons', models.IntegerField(blank=True, null=True)),
                ('draws', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('getgoals', models.IntegerField(blank=True, null=True)),
                ('lostgoals', models.IntegerField(blank=True, null=True)),
                ('get_losts', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('fouls', models.IntegerField(blank=True, null=True)),
                ('logos', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'k1_3라운드',
                'ordering': ('-points', '-getgoals'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kleague2_2021_1r',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('matches', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('wons', models.IntegerField(blank=True, null=True)),
                ('draws', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('getgoals', models.IntegerField(blank=True, null=True)),
                ('lostgoals', models.IntegerField(blank=True, null=True)),
                ('get_losts', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('fouls', models.IntegerField(blank=True, null=True)),
                ('logos', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'k2_1라운드',
                'ordering': ('-points', '-getgoals'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kleague2_2021_2r',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('matches', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('wons', models.IntegerField(blank=True, null=True)),
                ('draws', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('getgoals', models.IntegerField(blank=True, null=True)),
                ('lostgoals', models.IntegerField(blank=True, null=True)),
                ('get_losts', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('fouls', models.IntegerField(blank=True, null=True)),
                ('logos', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'k2_2라운드',
                'ordering': ('-points', '-getgoals'),
                'managed': False,
            },
        ),
    ]
