# Generated by Django 3.1.5 on 2021-03-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0002_auto_20210315_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='name',
        ),
    ]
