# Generated by Django 3.1.5 on 2021-03-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0003_auto_20210315_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
